
spring:
  datasource:
    url: jdbc:mysql://cognitive-app-db.mysql.database.azure.com:3306/cognitive_backend
    username: backend_user
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      static-locations: file:${IMAGE-DIRECTORY}
  mvc:
    static-path-pattern: /game_images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

springdoc:
  api-docs:
    path: /api-docs

app:
  python:
    source-location: ${PYTHON-DIRECTORY}/modellek.py
    models-location: ${PYTHON-DIRECTORY}/modellek
  thumbnail-location: ${IMAGE-DIRECTORY}
  image-path: http://localhost:8090/game_images