server:
  # Container port of the app
  port: 8090


spring:
  datasource:
    # Set the MySQL instance as the datasource that is available for the conatiner
    url: jdbc:mysql://${DATABASE_URL}:3306/cognitive_app
    username: dev
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      static-locations: file:${THUMBNAIL_PATH}
  mvc:
    static-path-pattern: /game_images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}

llms:
  mistral:
    api-key: ${MISTRAL_API_KEY}

app:
  python:
    exists: false
  thumbnail-location: ${THUMBNAIL_PATH}
  image-path: ${RESOURCE_SERVER_URL}/game_images