server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cognitive_app
    username: dev
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      static-locations: file:/Users/annav/Documents/Bme/Szakdoli/Kepessegteszt-backend/game_images/
  mvc:
    static-path-pattern: /game_images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cognitiveapp-authentication.northeurope.azurecontainer.io
          ##http://localhost:9000

springdoc:
  api-docs:
    path: /api-docs

app:
  python:
    source-location: C:/Users/strbi/Python_projects/Neural_network
    models-location: C:/Users/strbi/Python_projects/
  thumbnail-location: C:/Users/annav/Documents/Bme/Szakdoli/Kepessegteszt-backend/game_images/
  image-path: http://localhost:8090/game_images