server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cognitive_app
    username: dev
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      static-locations: file:/Users/annav/Documents/Bme/Szakdoli/Kepessegteszt-backend/game_images
  mvc:
    static-path-pattern: /game_images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

app:
  python:
    source-location: C:/Users/strbi/Python_projects/HelloWorld
    models-location: C:/Users/strbi/Python_projects/HelloWorld