server:
  port: 80
spring:
#  datasource:
#    url: jdbc:mysql://cognitive-app-db-eu.mysql.database.azure.com:3306/cognitive_backend?serverTimezone=UTC
#    username: backend_user
#    password: dev.1122
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:h2:mem:cogni-testDB;MODE=MYSQL;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      static-locations: file:${THUMBNAIL_PATH}
  mvc:
    static-path-pattern: /game_images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://cognitiveapp-authentication.northeurope.azurecontainer.io

springdoc:
  api-docs:
    path: /api-docs

app:
  python:
    source-location: ${PYTHON_PATH}
    models-location: ${PYTHON_PATH}/modellek/
  thumbnail-location: ${THUMBNAIL_PATH}
  image-path: http://localhost:8090/game_images