server:
  # Container port of the app
  port: 443


spring:
  datasource:
    # Set the MySQL instance as the datasource that is available for the conatiner
    url: jdbc:mysql://cognitive-app-db-eu.mysql.database.azure.com:3306/cognitive_backend?serverTimezone=UTC
    username: backend_user
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      static-locations: file:${THUMBNAIL_PATH}
  mvc:
    static-path-pattern: /game_images/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}


app:
  python:
    source-location: ${PYTHON_PATH}
    models-location: ${PYTHON_PATH}/modellek/
  thumbnail-location: ${THUMBNAIL_PATH}
  image-path: ${RESOURCE_SERVER_URL}/game_images