export const cognitive_profile_text = {
    title_user: 'kognitív profilja',
    chart: {
        chart_title: 'Kognitív profil az elmúlt időszakban',
        chart_description: 'A kognitív profilban szereplő képességek, és értékük az elmúlt időszakban',
    },
    radar_chart: {
        chart_title: 'Kognitív profil összehasonlítása',
        profile: 'Saját profil',
        avg_in_group: 'Átlagos értékek',
        max_in_group: 'Maximum értékek',
        min_in_group: 'Minimum értékek',
    },
    card: {
        current_profile: 'Legfrissebb kognitív profil',
        current_profile_description: 'A kognitív profilban szereplő képességek, és értékük ebben az időpontban: ',
        no_profile_data_message: 'Nincs elég adat, ezért nem lehet megjeleníteni a kognitív profilt.',
        no_profile_data_action: 'Több játék játszása esetén összeáll a kognitív profil.',
        abilities: 'Kognitív képességek',
        values: 'Becsült értékek',
        ability_value_accuracy: 'Kognitív profil érték pontosság: ',
    },
    user_picker: {
        choose_contact: 'Kognitív profil megtekintése',
        choose_contact_description: 'Válaszd ki, kinek a kognitív profilját szeretnéd megtekinteni',
        select: 'Megtekintés',
    },
    llm: {
        prompt: 'Prompt',
        prompt_description: 'Próbáld ki egyedi kérdés megadásával a kognitív profil elemzését.',
        prompt_action: 'Profil kiértékelés a megadott kérdés alapján',
        used_prompt: 'Használt prompt',
        llm_text: 'Elemzés',
        empty_description: 'Sajnos nem lehet elkészíteni az elemzést, mert nincs elég adat.',
    },
    date_picker: {
        see_history: 'Megtekintés korábbi időpontban',
        see_history_description: 'Válassz egy kezdő és egy végdátumot, hogy megtekinthesd a kognitív profilodat az adott időpontban.',
        see_history_action: 'Kognitív profil megtekintése',
    },
    comparison: {
        title: 'Kognitív profil elemzése',
        no_data: 'Nincs elég adat az összehasonlításhoz.',
        description: 'Válaszd ki, mely csoport adatait szeretnéd összehasonlítani a sajátoddal',
        avg: 'Átlag',
        min: 'Minimum',
        max: 'Maximum',
        comparison_type: 'Összehasonlítás típusa',
        comparison_type_description: 'Válaszd ki, milyen módon legyenek összehasonlítva a kognitív profil adatok a többi felhasználó adataival.',
        group_selection: 'Csoport kiválasztása',
        submit: 'Összehasonlítás',
        error_group_required: 'Válassz ki egy csoportot az összehasonlításhoz',
        error_type_required: 'Válassz ki egy összehasonlítási típust',
        error_no_group: 'Úgy látszik, egyetlen csoportnak sem vagy még tagja',
        composite_filter_title: 'Felhasználók részletes szűrése',
        composite_filter_description: 'Kontrollcsoport kijelölése több szűrő használatával',
        data_own: 'Saját kognitív profil érték',
        data_group: 'Csoport összesített értéke',
    },
    user_filter: {
        title: 'Felhasználók szűrése',
        description: 'Válaszd ki, milyen kritériumok alapján szeretnéd kiválasztani az összehasonlítás alapjául szolgáló felhasználói csoportot.',
        age: 'Életkor',
        age_min: 'Minimum kor',
        age_max: 'Maximum kor',
        ability: 'Kognitív képesség',
        ability_min: 'Minimum érték',
        ability_max: 'Maximum érték',
        group: 'Felhasználói csoport',
        group_selection: 'Csoport kiválasztása',
        address: 'Lakóhely',
        address_city: 'Város',
        address_zip: 'Irányítószám',
        submit: 'Szűrés',
    },
    profile_edit: {
        title_edit: 'Kognitív profil szerkesztése',
        title_user: 'kognitív profilja',
        choose_contact: 'Kognitív profil megtekintése és szerkesztése',
        choose_contact_description: 'Válaszd ki, kinek a kognitív profilját szeretnéd megtekinteni, ezután megjelennek a szerkeszthető értékek',
        description_edit: 'A felhasználó korábban mért képességértékei megadhatók, így ez lesz az aktuális kognitív profil.' +
            ' Minden képességhez beállítható a feltételezett érték.' +
            ' Ez befolyásolja a játékajánlásokat is. Az is megadható, hogy mennyire valószínű a beállított érték.',
        enum_profile_form: 'Speciális képességek',
        enum_profile_form_description: 'Ezekről a képességekről azt lehet megmondani, hogy rendelkezik-e vele a felhasználó.',
        float_profile_form: 'Általános mért képességek',
        float_profile_form_description: 'Ezekről a képességekről megállapítható számszerű érték. 1.0 jelenti az átlagosnak tekinthető értéket.',
        value: 'Kognitív képesség érték',
        accuracy: 'Pontosság',
        accuracy_validation_error: 'A pontosság értéke 0 és 1 között lehet.',
        value_unknown: 'Ismeretlen',
        value_yes: 'Igen',
        value_no: 'Nem',
        value_possible: 'Lehetséges',
        value_inclined: 'Hajlamos',
        save: 'Mentés',
    }
}