server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL}:3306/app_users
    username: dev
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

cognitive-app:
  issuer-url: ${URL}