server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app_users
    username: dev
    password: dev.1122
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#  profiles:
#    active: test

logging:
  level:
    org:
      springframework:
        security: info
        data:
          repository: trace
