name: Pull Request Build & Test

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test-auth-server:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        working-directory: backend/auth_server
        run: chmod +x ./gradlew

      - name: Build and run tests
        working-directory: backend/auth_server
        run: ./gradlew clean build

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            backend/auth_server/build/reports/tests/
            backend/auth_server/build/test-results/
            
  build-and-test-resource-server:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source resource-server
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        working-directory: backend/resource_server
        run: chmod +x ./gradlew

      - name: Run business critical coverage
        working-directory: backend/resource_server
        run: ./gradlew businessCriticalCoverage --info

      - name: Upload test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            backend/resource_server/build/reports/tests/
            backend/resource_server/build/test-results/
          
